# Generated by Django 4.2.4 on 2023-09-06 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="order",
        ),
    ]
