# Generated by Django 4.2.4 on 2023-09-06 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_category_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
