# Generated by Django 4.2.2 on 2023-09-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
